name: test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    paths:
    - '**.go'
    - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: go test -v -race ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34
